//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices", ConfigurationName="ServiceReference1.SolutionWebServiceSoap")]
    public interface SolutionWebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/RemoveSolutionComponent", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.RemoveSolutionComponentResponse> RemoveSolutionComponentAsync(ServiceReference1.RemoveSolutionComponentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/AddSolutionComponentList", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.AddSolutionComponentListResponse> AddSolutionComponentListAsync(ServiceReference1.AddSolutionComponentListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/CheckDependentComponents", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CheckDependentComponentsResponse> CheckDependentComponentsAsync(ServiceReference1.CheckDependentComponentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/HasSolutionComponents", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.HasSolutionComponentsResponse> HasSolutionComponentsAsync(ServiceReference1.HasSolutionComponentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/GetSiteMapId", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetSiteMapIdResponse> GetSiteMapIdAsync(ServiceReference1.GetSiteMapIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/IsSolutionMissingDependencies", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.IsSolutionMissingDependenciesResponse> IsSolutionMissingDependenciesAsync(ServiceReference1.IsSolutionMissingDependenciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/AddSolutionComponent", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.AddSolutionComponentResponse> AddSolutionComponentAsync(ServiceReference1.AddSolutionComponentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/CloneAsPatch", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CloneAsPatchResponse> CloneAsPatchAsync(ServiceReference1.CloneAsPatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/CloneAsSolution", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CloneAsSolutionResponse> CloneAsSolutionAsync(ServiceReference1.CloneAsSolutionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/GetSolutionName", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetSolutionNameResponse> GetSolutionNameAsync(ServiceReference1.GetSolutionNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/IsConfigurationIdEmpty", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.IsConfigurationIdEmptyResponse> IsConfigurationIdEmptyAsync(ServiceReference1.IsConfigurationIdEmptyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/AddComponentDependency", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.AddComponentDependencyResponse> AddComponentDependencyAsync(ServiceReference1.AddComponentDependencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/GetNumberPrefix", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetNumberPrefixResponse> GetNumberPrefixAsync(ServiceReference1.GetNumberPrefixRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/RefreshNavigationTree", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.RefreshNavigationTreeResponse> RefreshNavigationTreeAsync(ServiceReference1.RefreshNavigationTreeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/VerifySolutionIsPatch", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.VerifySolutionIsPatchResponse> VerifySolutionIsPatchAsync(ServiceReference1.VerifySolutionIsPatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/CreateSubFilterHtml", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CreateSubFilterHtmlResponse> CreateSubFilterHtmlAsync(ServiceReference1.CreateSubFilterHtmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/DeleteSolution", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.DeleteSolutionResponse> DeleteSolutionAsync(ServiceReference1.DeleteSolutionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/PromoteSolution", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.PromoteSolutionResponse> PromoteSolutionAsync(ServiceReference1.PromoteSolutionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveSolutionComponentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveSolutionComponent", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.RemoveSolutionComponentRequestBody Body;
        
        public RemoveSolutionComponentRequest()
        {
        }
        
        public RemoveSolutionComponentRequest(ServiceReference1.RemoveSolutionComponentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class RemoveSolutionComponentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement data;
        
        public RemoveSolutionComponentRequestBody()
        {
        }
        
        public RemoveSolutionComponentRequestBody(System.Xml.XmlElement data)
        {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveSolutionComponentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveSolutionComponentResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.RemoveSolutionComponentResponseBody Body;
        
        public RemoveSolutionComponentResponse()
        {
        }
        
        public RemoveSolutionComponentResponse(ServiceReference1.RemoveSolutionComponentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class RemoveSolutionComponentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RemoveSolutionComponentResult;
        
        public RemoveSolutionComponentResponseBody()
        {
        }
        
        public RemoveSolutionComponentResponseBody(string RemoveSolutionComponentResult)
        {
            this.RemoveSolutionComponentResult = RemoveSolutionComponentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSolutionComponentListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSolutionComponentList", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.AddSolutionComponentListRequestBody Body;
        
        public AddSolutionComponentListRequest()
        {
        }
        
        public AddSolutionComponentListRequest(ServiceReference1.AddSolutionComponentListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class AddSolutionComponentListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement data;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int addDependentComponent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long timeSpentOnClient;
        
        public AddSolutionComponentListRequestBody()
        {
        }
        
        public AddSolutionComponentListRequestBody(System.Xml.XmlElement data, int addDependentComponent, long timeSpentOnClient)
        {
            this.data = data;
            this.addDependentComponent = addDependentComponent;
            this.timeSpentOnClient = timeSpentOnClient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSolutionComponentListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSolutionComponentListResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.AddSolutionComponentListResponseBody Body;
        
        public AddSolutionComponentListResponse()
        {
        }
        
        public AddSolutionComponentListResponse(ServiceReference1.AddSolutionComponentListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class AddSolutionComponentListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddSolutionComponentListResult;
        
        public AddSolutionComponentListResponseBody()
        {
        }
        
        public AddSolutionComponentListResponseBody(string AddSolutionComponentListResult)
        {
            this.AddSolutionComponentListResult = AddSolutionComponentListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckDependentComponentsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckDependentComponents", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.CheckDependentComponentsRequestBody Body;
        
        public CheckDependentComponentsRequest()
        {
        }
        
        public CheckDependentComponentsRequest(ServiceReference1.CheckDependentComponentsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class CheckDependentComponentsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement data;
        
        public CheckDependentComponentsRequestBody()
        {
        }
        
        public CheckDependentComponentsRequestBody(System.Xml.XmlElement data)
        {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckDependentComponentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckDependentComponentsResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.CheckDependentComponentsResponseBody Body;
        
        public CheckDependentComponentsResponse()
        {
        }
        
        public CheckDependentComponentsResponse(ServiceReference1.CheckDependentComponentsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class CheckDependentComponentsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckDependentComponentsResult;
        
        public CheckDependentComponentsResponseBody()
        {
        }
        
        public CheckDependentComponentsResponseBody(string CheckDependentComponentsResult)
        {
            this.CheckDependentComponentsResult = CheckDependentComponentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HasSolutionComponentsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HasSolutionComponents", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.HasSolutionComponentsRequestBody Body;
        
        public HasSolutionComponentsRequest()
        {
        }
        
        public HasSolutionComponentsRequest(ServiceReference1.HasSolutionComponentsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class HasSolutionComponentsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string objectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int objectType;
        
        public HasSolutionComponentsRequestBody()
        {
        }
        
        public HasSolutionComponentsRequestBody(string objectId, int objectType)
        {
            this.objectId = objectId;
            this.objectType = objectType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HasSolutionComponentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HasSolutionComponentsResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.HasSolutionComponentsResponseBody Body;
        
        public HasSolutionComponentsResponse()
        {
        }
        
        public HasSolutionComponentsResponse(ServiceReference1.HasSolutionComponentsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class HasSolutionComponentsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool HasSolutionComponentsResult;
        
        public HasSolutionComponentsResponseBody()
        {
        }
        
        public HasSolutionComponentsResponseBody(bool HasSolutionComponentsResult)
        {
            this.HasSolutionComponentsResult = HasSolutionComponentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSiteMapIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSiteMapId", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.GetSiteMapIdRequestBody Body;
        
        public GetSiteMapIdRequest()
        {
        }
        
        public GetSiteMapIdRequest(ServiceReference1.GetSiteMapIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSiteMapIdRequestBody
    {
        
        public GetSiteMapIdRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSiteMapIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSiteMapIdResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.GetSiteMapIdResponseBody Body;
        
        public GetSiteMapIdResponse()
        {
        }
        
        public GetSiteMapIdResponse(ServiceReference1.GetSiteMapIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class GetSiteMapIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSiteMapIdResult;
        
        public GetSiteMapIdResponseBody()
        {
        }
        
        public GetSiteMapIdResponseBody(string GetSiteMapIdResult)
        {
            this.GetSiteMapIdResult = GetSiteMapIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsSolutionMissingDependenciesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsSolutionMissingDependencies", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.IsSolutionMissingDependenciesRequestBody Body;
        
        public IsSolutionMissingDependenciesRequest()
        {
        }
        
        public IsSolutionMissingDependenciesRequest(ServiceReference1.IsSolutionMissingDependenciesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class IsSolutionMissingDependenciesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string solutionId;
        
        public IsSolutionMissingDependenciesRequestBody()
        {
        }
        
        public IsSolutionMissingDependenciesRequestBody(string solutionId)
        {
            this.solutionId = solutionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsSolutionMissingDependenciesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsSolutionMissingDependenciesResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.IsSolutionMissingDependenciesResponseBody Body;
        
        public IsSolutionMissingDependenciesResponse()
        {
        }
        
        public IsSolutionMissingDependenciesResponse(ServiceReference1.IsSolutionMissingDependenciesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class IsSolutionMissingDependenciesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsSolutionMissingDependenciesResult;
        
        public IsSolutionMissingDependenciesResponseBody()
        {
        }
        
        public IsSolutionMissingDependenciesResponseBody(bool IsSolutionMissingDependenciesResult)
        {
            this.IsSolutionMissingDependenciesResult = IsSolutionMissingDependenciesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSolutionComponentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSolutionComponent", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.AddSolutionComponentRequestBody Body;
        
        public AddSolutionComponentRequest()
        {
        }
        
        public AddSolutionComponentRequest(ServiceReference1.AddSolutionComponentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class AddSolutionComponentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string objectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int objectType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int addDependentComponent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool includeSubcomponent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool includeMetadata;
        
        public AddSolutionComponentRequestBody()
        {
        }
        
        public AddSolutionComponentRequestBody(string objectId, int objectType, int addDependentComponent, bool includeSubcomponent, bool includeMetadata)
        {
            this.objectId = objectId;
            this.objectType = objectType;
            this.addDependentComponent = addDependentComponent;
            this.includeSubcomponent = includeSubcomponent;
            this.includeMetadata = includeMetadata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSolutionComponentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSolutionComponentResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.AddSolutionComponentResponseBody Body;
        
        public AddSolutionComponentResponse()
        {
        }
        
        public AddSolutionComponentResponse(ServiceReference1.AddSolutionComponentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class AddSolutionComponentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddSolutionComponentResult;
        
        public AddSolutionComponentResponseBody()
        {
        }
        
        public AddSolutionComponentResponseBody(string AddSolutionComponentResult)
        {
            this.AddSolutionComponentResult = AddSolutionComponentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CloneAsPatchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CloneAsPatch", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.CloneAsPatchRequestBody Body;
        
        public CloneAsPatchRequest()
        {
        }
        
        public CloneAsPatchRequest(ServiceReference1.CloneAsPatchRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class CloneAsPatchRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parentSolutionName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string displayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string versionNumber;
        
        public CloneAsPatchRequestBody()
        {
        }
        
        public CloneAsPatchRequestBody(string parentSolutionName, string displayName, string versionNumber)
        {
            this.parentSolutionName = parentSolutionName;
            this.displayName = displayName;
            this.versionNumber = versionNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CloneAsPatchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CloneAsPatchResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.CloneAsPatchResponseBody Body;
        
        public CloneAsPatchResponse()
        {
        }
        
        public CloneAsPatchResponse(ServiceReference1.CloneAsPatchResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class CloneAsPatchResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CloneAsPatchResult;
        
        public CloneAsPatchResponseBody()
        {
        }
        
        public CloneAsPatchResponseBody(string CloneAsPatchResult)
        {
            this.CloneAsPatchResult = CloneAsPatchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CloneAsSolutionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CloneAsSolution", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.CloneAsSolutionRequestBody Body;
        
        public CloneAsSolutionRequest()
        {
        }
        
        public CloneAsSolutionRequest(ServiceReference1.CloneAsSolutionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class CloneAsSolutionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parentSolutionName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string displayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string versionNumber;
        
        public CloneAsSolutionRequestBody()
        {
        }
        
        public CloneAsSolutionRequestBody(string parentSolutionName, string displayName, string versionNumber)
        {
            this.parentSolutionName = parentSolutionName;
            this.displayName = displayName;
            this.versionNumber = versionNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CloneAsSolutionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CloneAsSolutionResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.CloneAsSolutionResponseBody Body;
        
        public CloneAsSolutionResponse()
        {
        }
        
        public CloneAsSolutionResponse(ServiceReference1.CloneAsSolutionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class CloneAsSolutionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CloneAsSolutionResult;
        
        public CloneAsSolutionResponseBody()
        {
        }
        
        public CloneAsSolutionResponseBody(string CloneAsSolutionResult)
        {
            this.CloneAsSolutionResult = CloneAsSolutionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSolutionNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSolutionName", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.GetSolutionNameRequestBody Body;
        
        public GetSolutionNameRequest()
        {
        }
        
        public GetSolutionNameRequest(ServiceReference1.GetSolutionNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class GetSolutionNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string solutionId;
        
        public GetSolutionNameRequestBody()
        {
        }
        
        public GetSolutionNameRequestBody(string solutionId)
        {
            this.solutionId = solutionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSolutionNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSolutionNameResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.GetSolutionNameResponseBody Body;
        
        public GetSolutionNameResponse()
        {
        }
        
        public GetSolutionNameResponse(ServiceReference1.GetSolutionNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class GetSolutionNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSolutionNameResult;
        
        public GetSolutionNameResponseBody()
        {
        }
        
        public GetSolutionNameResponseBody(string GetSolutionNameResult)
        {
            this.GetSolutionNameResult = GetSolutionNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsConfigurationIdEmptyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsConfigurationIdEmpty", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.IsConfigurationIdEmptyRequestBody Body;
        
        public IsConfigurationIdEmptyRequest()
        {
        }
        
        public IsConfigurationIdEmptyRequest(ServiceReference1.IsConfigurationIdEmptyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class IsConfigurationIdEmptyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string solutionId;
        
        public IsConfigurationIdEmptyRequestBody()
        {
        }
        
        public IsConfigurationIdEmptyRequestBody(string solutionId)
        {
            this.solutionId = solutionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsConfigurationIdEmptyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsConfigurationIdEmptyResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.IsConfigurationIdEmptyResponseBody Body;
        
        public IsConfigurationIdEmptyResponse()
        {
        }
        
        public IsConfigurationIdEmptyResponse(ServiceReference1.IsConfigurationIdEmptyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class IsConfigurationIdEmptyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsConfigurationIdEmptyResult;
        
        public IsConfigurationIdEmptyResponseBody()
        {
        }
        
        public IsConfigurationIdEmptyResponseBody(bool IsConfigurationIdEmptyResult)
        {
            this.IsConfigurationIdEmptyResult = IsConfigurationIdEmptyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddComponentDependencyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddComponentDependency", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.AddComponentDependencyRequestBody Body;
        
        public AddComponentDependencyRequest()
        {
        }
        
        public AddComponentDependencyRequest(ServiceReference1.AddComponentDependencyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class AddComponentDependencyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string objectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int objectType;
        
        public AddComponentDependencyRequestBody()
        {
        }
        
        public AddComponentDependencyRequestBody(string objectId, int objectType)
        {
            this.objectId = objectId;
            this.objectType = objectType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddComponentDependencyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddComponentDependencyResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.AddComponentDependencyResponseBody Body;
        
        public AddComponentDependencyResponse()
        {
        }
        
        public AddComponentDependencyResponse(ServiceReference1.AddComponentDependencyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddComponentDependencyResponseBody
    {
        
        public AddComponentDependencyResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNumberPrefixRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNumberPrefix", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.GetNumberPrefixRequestBody Body;
        
        public GetNumberPrefixRequest()
        {
        }
        
        public GetNumberPrefixRequest(ServiceReference1.GetNumberPrefixRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class GetNumberPrefixRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customizationPrefix;
        
        public GetNumberPrefixRequestBody()
        {
        }
        
        public GetNumberPrefixRequestBody(string customizationPrefix)
        {
            this.customizationPrefix = customizationPrefix;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNumberPrefixResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNumberPrefixResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.GetNumberPrefixResponseBody Body;
        
        public GetNumberPrefixResponse()
        {
        }
        
        public GetNumberPrefixResponse(ServiceReference1.GetNumberPrefixResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class GetNumberPrefixResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetNumberPrefixResult;
        
        public GetNumberPrefixResponseBody()
        {
        }
        
        public GetNumberPrefixResponseBody(int GetNumberPrefixResult)
        {
            this.GetNumberPrefixResult = GetNumberPrefixResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefreshNavigationTreeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RefreshNavigationTree", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.RefreshNavigationTreeRequestBody Body;
        
        public RefreshNavigationTreeRequest()
        {
        }
        
        public RefreshNavigationTreeRequest(ServiceReference1.RefreshNavigationTreeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RefreshNavigationTreeRequestBody
    {
        
        public RefreshNavigationTreeRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefreshNavigationTreeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RefreshNavigationTreeResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.RefreshNavigationTreeResponseBody Body;
        
        public RefreshNavigationTreeResponse()
        {
        }
        
        public RefreshNavigationTreeResponse(ServiceReference1.RefreshNavigationTreeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class RefreshNavigationTreeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RefreshNavigationTreeResult;
        
        public RefreshNavigationTreeResponseBody()
        {
        }
        
        public RefreshNavigationTreeResponseBody(string RefreshNavigationTreeResult)
        {
            this.RefreshNavigationTreeResult = RefreshNavigationTreeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifySolutionIsPatchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifySolutionIsPatch", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.VerifySolutionIsPatchRequestBody Body;
        
        public VerifySolutionIsPatchRequest()
        {
        }
        
        public VerifySolutionIsPatchRequest(ServiceReference1.VerifySolutionIsPatchRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class VerifySolutionIsPatchRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string solutionUniqueName;
        
        public VerifySolutionIsPatchRequestBody()
        {
        }
        
        public VerifySolutionIsPatchRequestBody(string solutionUniqueName)
        {
            this.solutionUniqueName = solutionUniqueName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifySolutionIsPatchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifySolutionIsPatchResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.VerifySolutionIsPatchResponseBody Body;
        
        public VerifySolutionIsPatchResponse()
        {
        }
        
        public VerifySolutionIsPatchResponse(ServiceReference1.VerifySolutionIsPatchResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class VerifySolutionIsPatchResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifySolutionIsPatchResult;
        
        public VerifySolutionIsPatchResponseBody()
        {
        }
        
        public VerifySolutionIsPatchResponseBody(bool VerifySolutionIsPatchResult)
        {
            this.VerifySolutionIsPatchResult = VerifySolutionIsPatchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateSubFilterHtmlRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateSubFilterHtml", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.CreateSubFilterHtmlRequestBody Body;
        
        public CreateSubFilterHtmlRequest()
        {
        }
        
        public CreateSubFilterHtmlRequest(ServiceReference1.CreateSubFilterHtmlRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class CreateSubFilterHtmlRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int componentType;
        
        public CreateSubFilterHtmlRequestBody()
        {
        }
        
        public CreateSubFilterHtmlRequestBody(int componentType)
        {
            this.componentType = componentType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateSubFilterHtmlResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateSubFilterHtmlResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.CreateSubFilterHtmlResponseBody Body;
        
        public CreateSubFilterHtmlResponse()
        {
        }
        
        public CreateSubFilterHtmlResponse(ServiceReference1.CreateSubFilterHtmlResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class CreateSubFilterHtmlResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateSubFilterHtmlResult;
        
        public CreateSubFilterHtmlResponseBody()
        {
        }
        
        public CreateSubFilterHtmlResponseBody(string CreateSubFilterHtmlResult)
        {
            this.CreateSubFilterHtmlResult = CreateSubFilterHtmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSolutionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSolution", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.DeleteSolutionRequestBody Body;
        
        public DeleteSolutionRequest()
        {
        }
        
        public DeleteSolutionRequest(ServiceReference1.DeleteSolutionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class DeleteSolutionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string importJobId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id;
        
        public DeleteSolutionRequestBody()
        {
        }
        
        public DeleteSolutionRequestBody(string importJobId, string id)
        {
            this.importJobId = importJobId;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSolutionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSolutionResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.DeleteSolutionResponseBody Body;
        
        public DeleteSolutionResponse()
        {
        }
        
        public DeleteSolutionResponse(ServiceReference1.DeleteSolutionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteSolutionResponseBody
    {
        
        public DeleteSolutionResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PromoteSolutionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PromoteSolution", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.PromoteSolutionRequestBody Body;
        
        public PromoteSolutionRequest()
        {
        }
        
        public PromoteSolutionRequest(ServiceReference1.PromoteSolutionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class PromoteSolutionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parentSolutionUniqueName;
        
        public PromoteSolutionRequestBody()
        {
        }
        
        public PromoteSolutionRequestBody(string parentSolutionUniqueName)
        {
            this.parentSolutionUniqueName = parentSolutionUniqueName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PromoteSolutionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PromoteSolutionResponse", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public ServiceReference1.PromoteSolutionResponseBody Body;
        
        public PromoteSolutionResponse()
        {
        }
        
        public PromoteSolutionResponse(ServiceReference1.PromoteSolutionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PromoteSolutionResponseBody
    {
        
        public PromoteSolutionResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SolutionWebServiceSoapChannel : ServiceReference1.SolutionWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SolutionWebServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference1.SolutionWebServiceSoap>, ServiceReference1.SolutionWebServiceSoap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SolutionWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SolutionWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), SolutionWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SolutionWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SolutionWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SolutionWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SolutionWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SolutionWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.RemoveSolutionComponentResponse> ServiceReference1.SolutionWebServiceSoap.RemoveSolutionComponentAsync(ServiceReference1.RemoveSolutionComponentRequest request)
        {
            return base.Channel.RemoveSolutionComponentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RemoveSolutionComponentResponse> RemoveSolutionComponentAsync(System.Xml.XmlElement data)
        {
            ServiceReference1.RemoveSolutionComponentRequest inValue = new ServiceReference1.RemoveSolutionComponentRequest();
            inValue.Body = new ServiceReference1.RemoveSolutionComponentRequestBody();
            inValue.Body.data = data;
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).RemoveSolutionComponentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.AddSolutionComponentListResponse> ServiceReference1.SolutionWebServiceSoap.AddSolutionComponentListAsync(ServiceReference1.AddSolutionComponentListRequest request)
        {
            return base.Channel.AddSolutionComponentListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AddSolutionComponentListResponse> AddSolutionComponentListAsync(System.Xml.XmlElement data, int addDependentComponent, long timeSpentOnClient)
        {
            ServiceReference1.AddSolutionComponentListRequest inValue = new ServiceReference1.AddSolutionComponentListRequest();
            inValue.Body = new ServiceReference1.AddSolutionComponentListRequestBody();
            inValue.Body.data = data;
            inValue.Body.addDependentComponent = addDependentComponent;
            inValue.Body.timeSpentOnClient = timeSpentOnClient;
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).AddSolutionComponentListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CheckDependentComponentsResponse> ServiceReference1.SolutionWebServiceSoap.CheckDependentComponentsAsync(ServiceReference1.CheckDependentComponentsRequest request)
        {
            return base.Channel.CheckDependentComponentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CheckDependentComponentsResponse> CheckDependentComponentsAsync(System.Xml.XmlElement data)
        {
            ServiceReference1.CheckDependentComponentsRequest inValue = new ServiceReference1.CheckDependentComponentsRequest();
            inValue.Body = new ServiceReference1.CheckDependentComponentsRequestBody();
            inValue.Body.data = data;
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).CheckDependentComponentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.HasSolutionComponentsResponse> ServiceReference1.SolutionWebServiceSoap.HasSolutionComponentsAsync(ServiceReference1.HasSolutionComponentsRequest request)
        {
            return base.Channel.HasSolutionComponentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.HasSolutionComponentsResponse> HasSolutionComponentsAsync(string objectId, int objectType)
        {
            ServiceReference1.HasSolutionComponentsRequest inValue = new ServiceReference1.HasSolutionComponentsRequest();
            inValue.Body = new ServiceReference1.HasSolutionComponentsRequestBody();
            inValue.Body.objectId = objectId;
            inValue.Body.objectType = objectType;
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).HasSolutionComponentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetSiteMapIdResponse> ServiceReference1.SolutionWebServiceSoap.GetSiteMapIdAsync(ServiceReference1.GetSiteMapIdRequest request)
        {
            return base.Channel.GetSiteMapIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetSiteMapIdResponse> GetSiteMapIdAsync()
        {
            ServiceReference1.GetSiteMapIdRequest inValue = new ServiceReference1.GetSiteMapIdRequest();
            inValue.Body = new ServiceReference1.GetSiteMapIdRequestBody();
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).GetSiteMapIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.IsSolutionMissingDependenciesResponse> ServiceReference1.SolutionWebServiceSoap.IsSolutionMissingDependenciesAsync(ServiceReference1.IsSolutionMissingDependenciesRequest request)
        {
            return base.Channel.IsSolutionMissingDependenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.IsSolutionMissingDependenciesResponse> IsSolutionMissingDependenciesAsync(string solutionId)
        {
            ServiceReference1.IsSolutionMissingDependenciesRequest inValue = new ServiceReference1.IsSolutionMissingDependenciesRequest();
            inValue.Body = new ServiceReference1.IsSolutionMissingDependenciesRequestBody();
            inValue.Body.solutionId = solutionId;
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).IsSolutionMissingDependenciesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.AddSolutionComponentResponse> ServiceReference1.SolutionWebServiceSoap.AddSolutionComponentAsync(ServiceReference1.AddSolutionComponentRequest request)
        {
            return base.Channel.AddSolutionComponentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AddSolutionComponentResponse> AddSolutionComponentAsync(string objectId, int objectType, int addDependentComponent, bool includeSubcomponent, bool includeMetadata)
        {
            ServiceReference1.AddSolutionComponentRequest inValue = new ServiceReference1.AddSolutionComponentRequest();
            inValue.Body = new ServiceReference1.AddSolutionComponentRequestBody();
            inValue.Body.objectId = objectId;
            inValue.Body.objectType = objectType;
            inValue.Body.addDependentComponent = addDependentComponent;
            inValue.Body.includeSubcomponent = includeSubcomponent;
            inValue.Body.includeMetadata = includeMetadata;
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).AddSolutionComponentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CloneAsPatchResponse> ServiceReference1.SolutionWebServiceSoap.CloneAsPatchAsync(ServiceReference1.CloneAsPatchRequest request)
        {
            return base.Channel.CloneAsPatchAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CloneAsPatchResponse> CloneAsPatchAsync(string parentSolutionName, string displayName, string versionNumber)
        {
            ServiceReference1.CloneAsPatchRequest inValue = new ServiceReference1.CloneAsPatchRequest();
            inValue.Body = new ServiceReference1.CloneAsPatchRequestBody();
            inValue.Body.parentSolutionName = parentSolutionName;
            inValue.Body.displayName = displayName;
            inValue.Body.versionNumber = versionNumber;
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).CloneAsPatchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CloneAsSolutionResponse> ServiceReference1.SolutionWebServiceSoap.CloneAsSolutionAsync(ServiceReference1.CloneAsSolutionRequest request)
        {
            return base.Channel.CloneAsSolutionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CloneAsSolutionResponse> CloneAsSolutionAsync(string parentSolutionName, string displayName, string versionNumber)
        {
            ServiceReference1.CloneAsSolutionRequest inValue = new ServiceReference1.CloneAsSolutionRequest();
            inValue.Body = new ServiceReference1.CloneAsSolutionRequestBody();
            inValue.Body.parentSolutionName = parentSolutionName;
            inValue.Body.displayName = displayName;
            inValue.Body.versionNumber = versionNumber;
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).CloneAsSolutionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetSolutionNameResponse> ServiceReference1.SolutionWebServiceSoap.GetSolutionNameAsync(ServiceReference1.GetSolutionNameRequest request)
        {
            return base.Channel.GetSolutionNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetSolutionNameResponse> GetSolutionNameAsync(string solutionId)
        {
            ServiceReference1.GetSolutionNameRequest inValue = new ServiceReference1.GetSolutionNameRequest();
            inValue.Body = new ServiceReference1.GetSolutionNameRequestBody();
            inValue.Body.solutionId = solutionId;
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).GetSolutionNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.IsConfigurationIdEmptyResponse> ServiceReference1.SolutionWebServiceSoap.IsConfigurationIdEmptyAsync(ServiceReference1.IsConfigurationIdEmptyRequest request)
        {
            return base.Channel.IsConfigurationIdEmptyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.IsConfigurationIdEmptyResponse> IsConfigurationIdEmptyAsync(string solutionId)
        {
            ServiceReference1.IsConfigurationIdEmptyRequest inValue = new ServiceReference1.IsConfigurationIdEmptyRequest();
            inValue.Body = new ServiceReference1.IsConfigurationIdEmptyRequestBody();
            inValue.Body.solutionId = solutionId;
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).IsConfigurationIdEmptyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.AddComponentDependencyResponse> ServiceReference1.SolutionWebServiceSoap.AddComponentDependencyAsync(ServiceReference1.AddComponentDependencyRequest request)
        {
            return base.Channel.AddComponentDependencyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AddComponentDependencyResponse> AddComponentDependencyAsync(string objectId, int objectType)
        {
            ServiceReference1.AddComponentDependencyRequest inValue = new ServiceReference1.AddComponentDependencyRequest();
            inValue.Body = new ServiceReference1.AddComponentDependencyRequestBody();
            inValue.Body.objectId = objectId;
            inValue.Body.objectType = objectType;
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).AddComponentDependencyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetNumberPrefixResponse> ServiceReference1.SolutionWebServiceSoap.GetNumberPrefixAsync(ServiceReference1.GetNumberPrefixRequest request)
        {
            return base.Channel.GetNumberPrefixAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetNumberPrefixResponse> GetNumberPrefixAsync(string customizationPrefix)
        {
            ServiceReference1.GetNumberPrefixRequest inValue = new ServiceReference1.GetNumberPrefixRequest();
            inValue.Body = new ServiceReference1.GetNumberPrefixRequestBody();
            inValue.Body.customizationPrefix = customizationPrefix;
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).GetNumberPrefixAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.RefreshNavigationTreeResponse> ServiceReference1.SolutionWebServiceSoap.RefreshNavigationTreeAsync(ServiceReference1.RefreshNavigationTreeRequest request)
        {
            return base.Channel.RefreshNavigationTreeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RefreshNavigationTreeResponse> RefreshNavigationTreeAsync()
        {
            ServiceReference1.RefreshNavigationTreeRequest inValue = new ServiceReference1.RefreshNavigationTreeRequest();
            inValue.Body = new ServiceReference1.RefreshNavigationTreeRequestBody();
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).RefreshNavigationTreeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.VerifySolutionIsPatchResponse> ServiceReference1.SolutionWebServiceSoap.VerifySolutionIsPatchAsync(ServiceReference1.VerifySolutionIsPatchRequest request)
        {
            return base.Channel.VerifySolutionIsPatchAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.VerifySolutionIsPatchResponse> VerifySolutionIsPatchAsync(string solutionUniqueName)
        {
            ServiceReference1.VerifySolutionIsPatchRequest inValue = new ServiceReference1.VerifySolutionIsPatchRequest();
            inValue.Body = new ServiceReference1.VerifySolutionIsPatchRequestBody();
            inValue.Body.solutionUniqueName = solutionUniqueName;
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).VerifySolutionIsPatchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CreateSubFilterHtmlResponse> ServiceReference1.SolutionWebServiceSoap.CreateSubFilterHtmlAsync(ServiceReference1.CreateSubFilterHtmlRequest request)
        {
            return base.Channel.CreateSubFilterHtmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreateSubFilterHtmlResponse> CreateSubFilterHtmlAsync(int componentType)
        {
            ServiceReference1.CreateSubFilterHtmlRequest inValue = new ServiceReference1.CreateSubFilterHtmlRequest();
            inValue.Body = new ServiceReference1.CreateSubFilterHtmlRequestBody();
            inValue.Body.componentType = componentType;
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).CreateSubFilterHtmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.DeleteSolutionResponse> ServiceReference1.SolutionWebServiceSoap.DeleteSolutionAsync(ServiceReference1.DeleteSolutionRequest request)
        {
            return base.Channel.DeleteSolutionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DeleteSolutionResponse> DeleteSolutionAsync(string importJobId, string id)
        {
            ServiceReference1.DeleteSolutionRequest inValue = new ServiceReference1.DeleteSolutionRequest();
            inValue.Body = new ServiceReference1.DeleteSolutionRequestBody();
            inValue.Body.importJobId = importJobId;
            inValue.Body.id = id;
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).DeleteSolutionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.PromoteSolutionResponse> ServiceReference1.SolutionWebServiceSoap.PromoteSolutionAsync(ServiceReference1.PromoteSolutionRequest request)
        {
            return base.Channel.PromoteSolutionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.PromoteSolutionResponse> PromoteSolutionAsync(string parentSolutionUniqueName)
        {
            ServiceReference1.PromoteSolutionRequest inValue = new ServiceReference1.PromoteSolutionRequest();
            inValue.Body = new ServiceReference1.PromoteSolutionRequestBody();
            inValue.Body.parentSolutionUniqueName = parentSolutionUniqueName;
            return ((ServiceReference1.SolutionWebServiceSoap)(this)).PromoteSolutionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SolutionWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SolutionWebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SolutionWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://crm-qas.lonsid.cn/qas/AppWebServices/Solution.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SolutionWebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://crm-qas.lonsid.cn/qas/AppWebServices/Solution.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SolutionWebServiceSoap,
            
            SolutionWebServiceSoap12,
        }
    }
}
